### ISSUE TITLE
Question about updating variable description

### ISSUE THREAD

**Issue by GabriellaS-K** [dmrodz/dataMeta#12]
Hi!
Thanks for a fab package! I don't understand how to update variable types and descriptions, as I add new variables to the datafrane. Its a very long dataframe and I don't want to enter all the variable names right now, can I update parts of it later without having to do the whole promt_linker() and running through them all again? 

Thank you

**Comment by dmrodz** [comment]
Hello!
I suggest using the build_linker function and save your code for ongoing
use, where you add the column names as they come using the names function.

Would that work for you?

Thanks!
D

**Comment by GabriellaS-K** [comment]
Hi! 
Thank you so much :) 

Yes it works well. I think what worries me is remembering to update the linker, the var_descs and the var_type in the same order, or the dictionary will have rows that don't correspond. 

But this works :D
