### ISSUE TITLE
A question not an issue

### ISSUE THREAD

**Issue by UTexas80** [dmrodz/dataMeta#3]
Hello - this is a great package; thank you! Not wanting to be Captain Obvious but how would you recommend using dataMeta for more than on dataframe in a project. Do you suggest one dictionary per dataframe than bind them together? Thank you in advance. Regards..

**Comment by dmrodz** [comment]
Thanks for your question!
Right now, the package does not have the capability of doing multiple
dictionaries at once, since the nature of each dataset might differ
slightly. I think your approach is the best right now.

Will look into this further! Thank you!

Dania Rodriguez
