### ISSUE TITLE
Adding a column for class of variable

### ISSUE THREAD

**Issue by jestarr** [dmrodz/dataMeta#5]
I stumbled upon this package when looking to create a data dictionary similar to the ones used for Tidy Tuesday's.  

Is there a feature to create a column that lists the class of the variable when creating the data dictionary?

**Comment by dmrodz** [comment]
Thanks for writing!
I don't have a feature for that right now but am currently working on a newer version that incorporates this and other things (i.e. skip patterns, validations, class, etc). In the meantime, you'd need to create your own variable to add the class for each.

**Comment by dmrodz** [comment]
@jestarr this functionality is now built into the `build_dict()` function.
