### ISSUE TITLE
Not listing complete range in variable options for a variable type 0

### ISSUE THREAD

**Issue by leilahawa** [dmrodz/dataMeta#6]
Hi, I have a variable that contains numeric IDs and I would like to include the range of IDs in the data dictionary. The variable type is set to 0, but the data dictionary only displays a subset of the range in the corresponding variable options: 10 - 999, when it should be 2-3691. Any ideas about how to fix this?

Thanks!

**Comment by dmrodz** [comment]
Hello!
Can you provide example code?
Can you try setting your variable class to numeric beforehand?

Please let me know

Thanks,
D


--
Dania M. Rodriguez
https://github.com/dmrodz
https://www.linkedin.com/in/dmrodz

**Comment by leilahawa** [comment]
Thanks, setting the variable class to numeric did the trick!
