### ISSUE TITLE
Variable name order in data dictionary

### ISSUE THREAD

**Issue by leilahawa** [dmrodz/dataMeta#7]
Hey,

Is it possible to maintain the order of the variables in the data dictionary so that it's the same as the linker instead of listing the variable names in alphabetical order?

Thanks,
Leila

**Comment by dmrodz** [comment]
At the moment, not automatically.
But, you can save your variable order from the linker and reorder the
dictionary using those.

Please let me know how it goes.

Thanks!

**Comment by leilahawa** [comment]
Hi,

I added numbering to the variable names as a work around. Thank you for the prompt response!

Best,
Leila

**Comment by GabriellaS-K** [comment]
@leilahawa how did you add numbers? literally 1_var1 in the order you wanted them? I am having this problem too

**Comment by GabriellaS-K** [comment]
or @dmrodz how might you use the linker order to reorder the dictionary? 
thank you!
