### ISSUE TITLE
build_linker taking named vector as input for variable_description

### ISSUE THREAD

**Issue by emmavestesson** [dmrodz/dataMeta#8]
Hi, 
I just came across your package and I think it is great. As I was trying it out, I realized that I wouldn't trust myself to make sure that the vectors variable_description and the variable_type is in the exact same order as the variables in my original data when I have a lot of variables. I've written a version of the `build_linker()` function that takes a named vector for the variable_description input and for show_unique_cases you specify the variables that you want to show unique cases. I tried it with the esoph data and I get the same results as with the function in the package (see example included). 

If you think this is something that you and others would find useful I can do a pull request and add a documented version of the function to the package. 

``` r
library(dataMeta)

# Variable description is named vector
variable_description <- c("agegp"='age groups', "alcgp"='alcohol consumption' , "tobgp"="tobacco consumption", "ncases"="number of cases", "ncontrols"= 'Number of controls')

## Only specify variables that you want unique cases to be shown for
show_unique_cases <- c('agegp')

build_linker2 <-function (my.data, variable_description, show_unique_cases) 
{
  variables <-tibble::enframe(variable_description) 
  orig_data <- tibble::tibble(var_name=names(my.data))
  df <- dplyr::left_join(orig_data, variables, by=c('var_name'='name'))
  df$var_type <- df$var_name %in% show_unique_cases
return(df)
}

linker <- build_linker2(esoph, variable_description, show_unique_cases)
dictionary <- build_dict(my.data = my.data, linker = linker, option_description = NULL, 
                         prompt_varopts = FALSE)
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmrodz** [comment]
Thanks I'll review soon with the rest of requests and features to be added. Stay tuned!

**Comment by dmrodz** [comment]
@emmavestesson, the linker will work with your original variable order. I've uploaded changes to the build_dict() to keep original variable order in the final dictionary as well.
